language: ruby
rvm: 2.1.0
script:
   "bundle exec rake"
before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - sudo apt-get update --fix-missing
   - sudo apt-get install -qq postgresql
   - sudo apt-get install -qq postgresql-server-dev-9.3
   - sudo apt-get install -qq libpq-dev
   - sleep 3
   - bundle install
   - bundle exec rake rackup &
   - sleep 5
branches:
  only:
    - testing